indices:
  nifty50:
    enabled: true
    symbol: NIFTY50
    description: Nifty 50 Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: false
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  banknifty:
    enabled: false
    symbol: BANKNIFTY
    description: Bank Nifty Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      quantity: 1
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 5
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 150
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  sensex:
    enabled: false
    symbol: SENSEX
    description: BSE Sensex Index
    max_concurrent_trades: 1
    timeframes:
      lower: 5minute
      upper: 15minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 5
      stop_loss:
        enabled: true
        atr:
          enabled: false
          multiplier: 2.5
        fixed:
          enabled: true
          points: 200
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: false
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_finance:
    enabled: false
    symbol: NIFTY_FINANCE
    description: Nifty Financial Services Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_it:
    enabled: false
    symbol: NIFTY_IT
    description: Nifty IT Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_realty:
    enabled: false
    symbol: NIFTY_REALTY
    description: Nifty Realty Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_infra:
    enabled: false
    symbol: NIFTY_INFRA
    description: Nifty Infrastructure Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_energy:
    enabled: false
    symbol: NIFTY_ENERGY
    description: Nifty Energy Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_fmcg:
    enabled: false
    symbol: NIFTY_FMCG
    description: Nifty FMCG Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_pharma:
    enabled: false
    symbol: NIFTY_PHARMA
    description: Nifty Pharma Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
  nifty_auto:
    enabled: false
    symbol: NIFTY_AUTO
    description: Nifty Auto Index
    max_concurrent_trades: 1
    timeframes:
      lower: 15minute
      upper: 60minute
    risk_management:
      capital: 100000
      risk_per_trade: 1
      quantity: 1
      max_open_trades: 3
      daily_max_loss: 3
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: true
          multiplier: 2
        fixed:
          enabled: false
          points: 45
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1
        candle_trailing:
          enabled: false
        step_trailing:
          enabled: true
          levels:
            - profit_r: 0.8
              lock_r: 0
            - profit_r: 1.5
              lock_r: 0.5
            - profit_r: 2.5
              lock_r: 1.5
trading_style: intraday
trading_hours:
  start_time: '09:15'
  end_time: '15:15'
indicators:
  ema:
    short: 20
    medium: 50
    long: 200
  rsi:
    #call_threshold (55): Minimum RSI value required to enter a Bullish (CALL) trade
    call_threshold: 55
    # call_upper_threshold (75): Maximum RSI value allowed for a CALL entry (prevents buying when overbought).
    call_upper_threshold: 70
    # put_threshold (45): Maximum RSI value required to enter a Bearish (PUT) trade.
    put_threshold: 45
    # put_lower_threshold (35): Minimum RSI value allowed for a PUT entry (prevents selling when oversold).
    put_lower_threshold: 35
    # upper_call_threshold (50): Minimum RSI value on the upper timeframe for a CALL entry.
    upper_call_threshold: 50
    # upper_call_max (70): Maximum RSI value on the upper timeframe for a CALL entry.
    upper_call_max: 70
    # upper_put_threshold (50): Maximum RSI value on the upper timeframe for a PUT entry.
    upper_put_threshold: 50
    #upper_put_min (30): Minimum RSI value allowed on the upper timeframe for a PUT entry.
    upper_put_min: 50
    # neutral_threshold (50): A baseline used in OptionStrategy to confirm trend alignment. Upper timeframe RSI must be above this for CALLs and below this for PUTs.
    neutral_threshold: 50
    exit:
      reversal_number: 5
  atr:
    period: 14
    multiplier: 1.5
    sl_multiplier: 1.5
    trail_multiplier: 1.2
  macd:
    enabled: true
    fast: 12
    slow: 26
    signal: 9
  stochastic:
    enabled: false
    k: 14
    d: 3
    smooth_k: 3
    oversold: 20
    overbought: 80
  adx:
    enabled: true
    dx_enabled: false
    period: 14
    threshold: 18
  trend_reversal_exit:
    enabled: true
    confirmation:
      doji: true
      market_structure: true
patterns:
  enabled: true
  bullish:
    is_hammer: true
    is_inverted_hammer: false
    is_dragonfly_doji: false
    is_bullish_spinning_top: false
    is_bullish_kicker: false
    is_bullish_engulfing: true
    is_piercing_line: true
    is_bullish_harami: false
    is_tweezer_bottom: false
    is_morning_doji_star: false
    is_three_white_soldiers: true
    is_bullish_engulfing_sandwich: false
    is_bullish_abandoned_baby: true
    is_morning_star: true
    is_rising_three: false
  bearish:
    is_hanging_man: false
    is_shooting_star: true
    is_gravestone_doji: false
    is_bearish_spinning_top: false
    is_bearish_engulfing: true
    is_bearish_kicker: false
    is_dark_cloud_cover: true
    is_bearish_harami: false
    is_tweezer_top: false
    is_falling_three: false
    is_bearish_engulfing_sandwich: false
    is_three_black_crows: true
    is_evening_doji_star: false
    is_bearish_abandoned_baby: true
    is_evening_star: true
  neutral:
    is_spinning_top: true
    is_doji: true
    is_harami: true
    is_marubozu: true
