indices:
  nifty50:
    enabled: true
    symbol: "NIFTY50"
    description: "Nifty 50 Index"
    max_concurrent_trades: 1
    timeframes:
      lower: "15minute"
      upper: "60minute"
      # lower: "5minute"
      # upper: "15minute"
    risk_management:
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: false
          multiplier: 1.2
        fixed:
          enabled: true
          points: 25
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1.0
        step_trailing:
          enabled: true
          levels:
            - { profit_r: 0.8, lock_r: 0.0 }
            - { profit_r: 1.5, lock_r: 0.5 }
            - { profit_r: 2.5, lock_r: 1.5 }

  banknifty:
    enabled: true
    symbol: "BANKNIFTY"
    description: "Bank Nifty Index"
    max_concurrent_trades: 1
    timeframes:
      lower: "15minute"
      upper: "60minute"
      # lower: "5minute"
      # upper: "15minute"
    risk_management:
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: false
          multiplier: 1.2
        fixed:
          enabled: true
          points: 50
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1.0
        step_trailing:
          enabled: true
          levels:
            - { profit_r: 0.8, lock_r: 0.0 }
            - { profit_r: 1.5, lock_r: 0.5 }
            - { profit_r: 2.5, lock_r: 1.5 }
  finnifty:
    enabled: false
    symbol: "FINNIFTY"
    description: "Nifty Financial Services"
    max_concurrent_trades: 1
    timeframes:
      lower: "15minute"
      upper: "60minute"
      # lower: "5minute"
      # upper: "15minute"
    risk_management:
      max_trades_per_day: 10
      max_consecutive_losses_per_day: 3
      stop_loss:
        enabled: true
        atr:
          enabled: false
          multiplier: 1.2
        fixed:
          enabled: true
          points: 20
      trailing:
        enabled: false
        activation_r: 1.5
        multiplier: 1.0
        step_trailing:
          enabled: true
          levels:
            - { profit_r: 0.8, lock_r: 0.0 }
            - { profit_r: 1.5, lock_r: 0.5 }
            - { profit_r: 2.5, lock_r: 1.5 }

trading_hours:
  start_time: "09:20"
  end_time: "15:00"

indicators:
  rsi:
    call_threshold: 60
    call_upper_threshold: 75
    put_threshold: 50
    put_lower_threshold: 35
    upper_call_threshold: 50
    upper_call_max: 75
    upper_put_threshold: 55
    upper_put_min: 30
    put_lower_threshold_old: 20
    neutral_threshold: 50
    exit:
      reversal_number: 5
  atr:
    period: 14
    multiplier: 1.5
    sl_multiplier: 1.5
    trail_multiplier: 1.2
  macd:
    enabled: true
    fast: 12
    slow: 26
    signal: 9
  stochastic:
    enabled: false
    k: 14
    d: 3
    smooth_k: 3
    oversold: 20
    overbought: 80

patterns:
  bullish:
    is_hammer: true
    is_inverted_hammer: false
    is_dragonfly_doji: false
    is_bullish_spinning_top: false
    is_bullish_kicker: false
    is_bullish_engulfing: true
    is_piercing_line: true
    is_bullish_harami: false
    is_tweezer_bottom: false
    is_morning_doji_star: false
    is_three_white_soldiers: true
    is_bullish_engulfing_sandwich: false
    is_bullish_abandoned_baby: true
    is_morning_star: true
    is_rising_three: false
  bearish:
    is_hanging_man: false
    is_shooting_star: true
    is_gravestone_doji: false
    is_bearish_spinning_top: false
    is_bearish_engulfing: true
    is_bearish_kicker: false
    is_dark_cloud_cover: true
    is_bearish_harami: false
    is_tweezer_top: false
    is_falling_three: false
    is_bearish_engulfing_sandwich: false
    is_three_black_crows: true
    is_evening_doji_star: false
    is_bearish_abandoned_baby: true
    is_evening_star: true
  neutral:
    is_spinning_top: true
    is_doji: true
    is_harami: true
    is_marubozu: true
